# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 554b9ec3d5a6be5e86a38f0ccfb41c1145b671bbb5b6d295083953b46663a1050fa7391f05c3c92a25ecac702b65f223e1ea0a32a5e2df074a38aca89df4bd7c

test:
  secret_key_base: 1d2fc82757874b43b8c26a2fd04ce0e9fb07e4b81b8a449ea63cfb5e13300b712dbfa91157b4f1520a14742d648e05bcf221cff970e368e02fa4b79e3d17de5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
